# Generated by Django 3.0.8 on 2020-09-01 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_auto_20200901_1602'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product',
            new_name='price',
        ),
    ]
